using System ;
using System . Collections ;
using System . Collections . Generic ;
using System . Linq ;

namespace DreamRecorder . CloudFileSystem
{

	public class DefaultSecurity
	{

		public static byte [ ] RootSecurity { get ; } = new byte [ ]
														{
															1 ,
															0 ,
															4 ,
															148 ,
															20 ,
															0 ,
															0 ,
															0 ,
															36 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															64 ,
															0 ,
															0 ,
															0 ,
															1 ,
															2 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															5 ,
															32 ,
															0 ,
															0 ,
															0 ,
															32 ,
															2 ,
															0 ,
															0 ,
															1 ,
															5 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															5 ,
															21 ,
															0 ,
															0 ,
															0 ,
															142 ,
															153 ,
															186 ,
															212 ,
															175 ,
															92 ,
															155 ,
															147 ,
															37 ,
															211 ,
															24 ,
															129 ,
															0 ,
															2 ,
															0 ,
															0 ,
															2 ,
															0 ,
															52 ,
															0 ,
															2 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															20 ,
															0 ,
															191 ,
															1 ,
															19 ,
															0 ,
															1 ,
															1 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															5 ,
															11 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															24 ,
															0 ,
															255 ,
															1 ,
															31 ,
															0 ,
															1 ,
															2 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															5 ,
															32 ,
															0 ,
															0 ,
															0 ,
															32 ,
															2 ,
															0 ,
															0 ,
														} ;

	}

}
