using System ;
using System . Collections ;
using System . Collections . Generic ;
using System . Linq ;

namespace DreamRecorder . CloudFileSystem
{

	public class DefaultSecurity
	{

		public static byte [ ] RootSecurity { get ; } = new byte[ 120 ]
														{
															1 ,
															0 ,
															4 ,
															148 ,
															20 ,
															0 ,
															0 ,
															0 ,
															32 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															44 ,
															0 ,
															0 ,
															0 ,
															1 ,
															1 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															5 ,
															18 ,
															0 ,
															0 ,
															0 ,
															1 ,
															1 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															5 ,
															18 ,
															0 ,
															0 ,
															0 ,
															2 ,
															0 ,
															76 ,
															0 ,
															3 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															20 ,
															0 ,
															255 ,
															1 ,
															31 ,
															0 ,
															1 ,
															1 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															5 ,
															18 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															24 ,
															0 ,
															255 ,
															1 ,
															31 ,
															0 ,
															1 ,
															2 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															5 ,
															32 ,
															0 ,
															0 ,
															0 ,
															32 ,
															2 ,
															0 ,
															0 ,
															0 ,
															0 ,
															24 ,
															0 ,
															191 ,
															1 ,
															19 ,
															0 ,
															1 ,
															2 ,
															0 ,
															0 ,
															0 ,
															0 ,
															0 ,
															5 ,
															32 ,
															0 ,
															0 ,
															0 ,
															33 ,
															2 ,
															0 ,
															0
														} ;

	}

}
